// <auto-generated />
namespace WeCountSvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tweaks2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tweaks2));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301424031_Tweaks2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
