// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GPSLocation
    {
        /// <summary>
        /// Initializes a new instance of the GPSLocation class.
        /// </summary>
        public GPSLocation() { }

        /// <summary>
        /// Initializes a new instance of the GPSLocation class.
        /// </summary>
        public GPSLocation(double? lat = default(double?), double? lon = default(double?), double? accuracy = default(double?))
        {
            Lat = lat;
            Lon = lon;
            Accuracy = accuracy;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lat")]
        public double? Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lon")]
        public double? Lon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public double? Accuracy { get; set; }

    }
}
