// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurveyQuestionAnswerChoiceResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SurveyQuestionAnswerChoiceResponseModel class.
        /// </summary>
        public SurveyQuestionAnswerChoiceResponseModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// SurveyQuestionAnswerChoiceResponseModel class.
        /// </summary>
        public SurveyQuestionAnswerChoiceResponseModel(int? questionID = default(int?), int? answerChoiceID = default(int?), string additionalAnswerData = default(string))
        {
            QuestionID = questionID;
            AnswerChoiceID = answerChoiceID;
            AdditionalAnswerData = additionalAnswerData;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuestionID")]
        public int? QuestionID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnswerChoiceID")]
        public int? AnswerChoiceID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalAnswerData")]
        public string AdditionalAnswerData { get; set; }

    }
}
