// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurveyQuestionAnswerChoiceModel
    {
        /// <summary>
        /// Initializes a new instance of the SurveyQuestionAnswerChoiceModel
        /// class.
        /// </summary>
        public SurveyQuestionAnswerChoiceModel() { }

        /// <summary>
        /// Initializes a new instance of the SurveyQuestionAnswerChoiceModel
        /// class.
        /// </summary>
        public SurveyQuestionAnswerChoiceModel(int? answerChoiceID = default(int?), string answerChoiceNum = default(string), string answerChoiceText = default(string), int? additionalAnswerDataFormat = default(int?), int? nextQuestionID = default(int?), bool? endSurvey = default(bool?))
        {
            AnswerChoiceID = answerChoiceID;
            AnswerChoiceNum = answerChoiceNum;
            AnswerChoiceText = answerChoiceText;
            AdditionalAnswerDataFormat = additionalAnswerDataFormat;
            NextQuestionID = nextQuestionID;
            EndSurvey = endSurvey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnswerChoiceID")]
        public int? AnswerChoiceID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnswerChoiceNum")]
        public string AnswerChoiceNum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnswerChoiceText")]
        public string AnswerChoiceText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalAnswerDataFormat")]
        public int? AdditionalAnswerDataFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NextQuestionID")]
        public int? NextQuestionID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndSurvey")]
        public bool? EndSurvey { get; set; }

    }
}
