// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurveyResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the SurveyResponseModel class.
        /// </summary>
        public SurveyResponseModel() { }

        /// <summary>
        /// Initializes a new instance of the SurveyResponseModel class.
        /// </summary>
        public SurveyResponseModel(int? surveyID = default(int?), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), Guid? responseIdentifier = default(Guid?), GPSLocation gPSLocation = default(GPSLocation), string locationNotes = default(string), Address nearestAddress = default(Address), IList<SurveyQuestionResponseModel> questionResponses = default(IList<SurveyQuestionResponseModel>))
        {
            SurveyID = surveyID;
            StartTime = startTime;
            EndTime = endTime;
            ResponseIdentifier = responseIdentifier;
            GPSLocation = gPSLocation;
            LocationNotes = locationNotes;
            NearestAddress = nearestAddress;
            QuestionResponses = questionResponses;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SurveyID")]
        public int? SurveyID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTime")]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndTime")]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseIdentifier")]
        public Guid? ResponseIdentifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GPSLocation")]
        public GPSLocation GPSLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocationNotes")]
        public string LocationNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NearestAddress")]
        public Address NearestAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuestionResponses")]
        public IList<SurveyQuestionResponseModel> QuestionResponses { get; set; }

    }
}
