// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurveySummaryModel
    {
        /// <summary>
        /// Initializes a new instance of the SurveySummaryModel class.
        /// </summary>
        public SurveySummaryModel() { }

        /// <summary>
        /// Initializes a new instance of the SurveySummaryModel class.
        /// </summary>
        public SurveySummaryModel(int? id = default(int?), string description = default(string), int? version = default(int?), DateTime? lastUpdated = default(DateTime?))
        {
            ID = id;
            Description = description;
            Version = version;
            LastUpdated = lastUpdated;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public int? Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastUpdated")]
        public DateTime? LastUpdated { get; set; }

    }
}
