// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurveyModel
    {
        /// <summary>
        /// Initializes a new instance of the SurveyModel class.
        /// </summary>
        public SurveyModel() { }

        /// <summary>
        /// Initializes a new instance of the SurveyModel class.
        /// </summary>
        public SurveyModel(int? surveyID = default(int?), string name = default(string), string description = default(string), string introText = default(string), IList<SurveyQuestionModel> questions = default(IList<SurveyQuestionModel>))
        {
            SurveyID = surveyID;
            Name = name;
            Description = description;
            IntroText = introText;
            Questions = questions;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SurveyID")]
        public int? SurveyID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IntroText")]
        public string IntroText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Questions")]
        public IList<SurveyQuestionModel> Questions { get; set; }

    }
}
