// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PITCSurveyLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class VolunteerModel
    {
        /// <summary>
        /// Initializes a new instance of the VolunteerModel class.
        /// </summary>
        public VolunteerModel() { }

        /// <summary>
        /// Initializes a new instance of the VolunteerModel class.
        /// </summary>
        public VolunteerModel(string firstName = default(string), string lastName = default(string), string email = default(string), string mobilePhone = default(string), string homePhone = default(string), Address address = default(Address))
        {
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            MobilePhone = mobilePhone;
            HomePhone = homePhone;
            Address = address;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MobilePhone")]
        public string MobilePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HomePhone")]
        public string HomePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public Address Address { get; set; }

    }
}
